# Generated by Django 6.1 on 2026-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
