# Generated by Django 6.1 on 2026-08-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='/profiles/default.png', upload_to='profiles/'),
        ),
    ]
