# Generated by Django 6.1 on 2026-09-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_employee_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager')], default='employee', max_length=20),
        ),
    ]
